package org.prog.cucumber.steps;

import io.cucumber.java.en.Given;
import org.prog.dto.PersonDto;
import org.prog.spring.db.Persons;
import org.prog.spring.db.PersonsJpa;
import org.prog.util.CucumberStorage;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.List;

public class SqlSteps {

    @Autowired
    private PersonsJpa personsJpa;

    @Given("I store {string} generated by API to our DB")
    public void storePeople(String alias) {
        List<PersonDto> persons = (List<PersonDto>) CucumberStorage.HOLDER.get(alias);
        for (PersonDto p : persons) {
            try {
                personsJpa.save(Persons.fromDto(p));
            } catch (Exception e) {
                System.out.println("Skip this person");
            }
        }
    }

    @Given("I pick a random person FirstName and LastName from DB as {string}")
    public void pickRandomperson(String alias) {
        Persons randomPerson = personsJpa.getRandomPerson().get();
        CucumberStorage.HOLDER.put(
                alias, randomPerson.getFirstName() + " " + randomPerson.getLastName());
    }
}
